### ISSUE TITLE
Set exif data

### ISSUE THREAD

**Issue by mpirescarvalho** [ApeironTsuka/node-webpmux#1]
It's possible to set exif data for **NOT ANIMATED** webp files?
I see the exif property but I'm not sure how could I save it back to a file

**Comment by ApeironTsuka** [comment]
It should be possible, but the .exif property is the raw, already-encoded EXIF data as it's found in the WEBP itself. It was outside the scope at the time to actually parse the EXIF chunk, and it's mostly kept (along with the XMP and ICC chunks) so that they don't get stripped out when re-saving WEBPs that have them defined.

**Comment by mpirescarvalho** [comment]
I have a `.webp` and a `.exif` file

using webpmux binary I could do:
`webpmux -set exif image_metadata.exif in.webp -o exif_container.webp`

would that be possible with this library?

**Comment by ApeironTsuka** [comment]
At the moment, no. There's currently no way to save non-animated WEBPs.

I'll see about adding the ability to save non-animated WEBPs later today. I should have time. This library was originally intended mostly for reading metadata (as I couldn't find anything out there, not even the webpmux binary, that would give me access to the level of detail I needed at the time about stored animations). However, I do see the benefit to having the ability to set EXIF/ICC/XMP like this and feel a little silly for not already implementing it properly.

**Comment by mpirescarvalho** [comment]
And just to mention:

https://github.com/ApeironTsuka/node-webpmux/blob/402ef27cfae7fef506f2b1131a124af8d74eaa5f/webp.mjs#L120-L121

I think this sould be:
```js
...createBasicChunk('EXIF', this.data.exif.raw)
```
instead of:
```js
...createBasicChunk('EXIF', this.data.extended.exif.raw)
```

**Comment by ApeironTsuka** [comment]
Just pushed an update containing a .save and a static Image.save. Also fixed the EXIF/XMP/ICC chunk saving, as you're right, it should've been `this.data.exif.raw`. Feel free to re-open this if the save function doesn't work as expected.

**Comment by mpirescarvalho** [comment]
I'm sorry, but there's still something wrong, and I couldn't figure out if it is on my end.

Take a look at these two images (github doesn't support webp, so I'm sending prints):

I used webpmux binary to set the exif data to this webp file, and it opens as expected:
![image](https://user-images.githubusercontent.com/20830847/114105718-a62d2600-98a3-11eb-99ea-69c562c496b2.png)

This other one I used your library to set the exif data, but it broke the image:
![image](https://user-images.githubusercontent.com/20830847/114105785-d2e13d80-98a3-11eb-9a91-fd8d2fdd9b3d.png)


Now, looking at the images as text, I can see that the binary generated one puts the exif data at the end:
![image](https://user-images.githubusercontent.com/20830847/114106024-4edb8580-98a4-11eb-9550-ef10e58347d6.png)

While your library puts it at the top:
![image](https://user-images.githubusercontent.com/20830847/114106103-73376200-98a4-11eb-89a6-43494e7dc50b.png)


Maybe this is causing the images to be broken?

This is how I'm setting the data:
```js
let img = new NodeWebP.Image();
await img.load(resultPath);
img.exif = exif
await img.save(resultPath);
```

It's the same data for both images

**Comment by ApeironTsuka** [comment]
Sorry about that. Never write code when half asleep and forget to _test_ afterwards. It should hopefully work now.

**Comment by mpirescarvalho** [comment]
It didn't work 🙁

Is there something I can do to help?

**Comment by ApeironTsuka** [comment]
I'm not really sure. From my (admittedly limited) testing using GIMP to write the metadata, it works as expected. Both extracting the EXIF chunk to file via the webpmux binary and this library, as well as setting the EXIF chunk produce identical, working images. Does it work when using the webpmux binary set the EXIF data? If it does, could you upload the images/EXIF file somewhere and I can take a look?

**Comment by mpirescarvalho** [comment]
> Does it work when using the webpmux binary set the EXIF data?
Yes, it works.

I've upload the files to [this repo](https://github.com/mpirescarvalho/node-webpmux-test)

Files:

- **exif-data.exif**: the actual exif data

- **raw-image.webp**: the original source image

- **webpmux-bin-image.webp**: the image that was created using [webpmux binary](https://developers.google.com/speed/webp/docs/webpmux)

- **node-webpmux-image.webp**: the image that was created using [node-webpmux](https://github.com/ApeironTsuka/node-webpmux)


Note that the [webpmux bin generated](https://raw.githubusercontent.com/mpirescarvalho/node-webpmux-test/master/webpmux-bin-image.webp) one opens normally, while the [node-webpmux generated](https://raw.githubusercontent.com/mpirescarvalho/node-webpmux-test/master/node-webpmux-image.webp) do not

**Comment by ApeironTsuka** [comment]
Thanks. Should be definitely fixed now. Tested by loading webpmux-bin-image.webp and saving it. Output is identical, and displays fine in Chrome. Turns out the order the chunks are saved matters more than I thought. I don't recall the documentation mentioning that the ALPH chunk **must** come before the VP8 chunk or it's not a valid image.

**Comment by mpirescarvalho** [comment]
It worked, many thanks!
