### ISSUE TITLE
Help Me Plis. #convertToExtended() unexpected token '('

### ISSUE THREAD

**Issue by Theblood** [ApeironTsuka/node-webpmux#10]
Hi, my problem is 

`/node_modules/node-webpmux/webp.js:441
  #convertToExtended() {
                    ^

SyntaxError: Unexpected token '('
`
Someone has had this error and if possible, how did they solve it?

**Comment by ApeironTsuka** [comment]
What version of Node are you using? It should work fine in versions 14.x and up, and I think as far back as 12.x with a couple experimental flags.

This error comes from Node being unable to parse private class function syntax.

**Comment by Nurutomo** [comment]
how can i use this in node 12.x ?

**Comment by ApeironTsuka** [comment]
The only 12.x I have on hand is 12.11.1, and with that you can use `node --harmony-private-methods`.

**Comment by Theblood** [comment]
Hi, 
Guys, this problem is version the node, but after upgrade of version 12 to 14  this is resolve my problem.!
