### ISSUE TITLE
SyntaxError: Invalid or unexpected token | Whatsapp-web.js

### ISSUE THREAD

**Issue by sathishkumarece** [ApeironTsuka/node-webpmux#14]
Hello,
I am using whatsapp-web.js for my project.
In that, node-webpmux is using as dependencies.

When I am trying to run the application I am getting 'SyntaxError: Invalid or unexpected token'
![image](https://user-images.githubusercontent.com/32127136/125567935-f199996c-0d2b-44de-a40f-eaf43fc20ca1.png)

Please check and support on this topic.

**Comment by PurpShell** [comment]
Bro please see the pinned issue i made before contacting node-webpmux! pedroslopez/whatsapp-web.js#688

**Comment by PurpShell** [comment]
also @ApeironTsuka do you have a Discord we can talk on?

**Comment by sathishkumarece** [comment]
Received response from Whatsapp-web repo. Thanks for the support. Closing this issue.
