### ISSUE TITLE
Issues with Node version

### ISSUE THREAD

**Issue by PurpShell** [ApeironTsuka/node-webpmux#16]
Hey Apeiron! Thanks for working on reducing the node version requirements to run this package. Surpsingly, the issue still persists after removing private field declarations in 3.1.0

**Comment by PurpShell** [comment]
"#convertToExtended() {" SyntaxError: Unexpected token ' ( ' in node_modules/node-webpmux/webp.js in line 441" is the issue, not sure if it is related to private fields :V

**Comment by PurpShell** [comment]
A user using REPL.it is also facing the issue, note that he selected node-14, not sure how we are going to diagnose this :/

pedroslopez/whatsapp-web.js#798

**Comment by ApeironTsuka** [comment]
That particular error means they're definitely not using 3.1.0. As for it not working in Safari.. that I have no idea without more information as I don't have Safari to test with.

**Comment by PurpShell** [comment]
well i think they updated before you did. We seem to have fixed the issue! I am pretty confused atm lol, seems like npm has done some shenanigans (`^3.0.0` wasn't the same as `^3.1.0`). Have a good day! Also if you would like to talk, talk to me on discord: PurpShell#0001
