### ISSUE TITLE
Cannot read properties of undefined (reading 'vp8')

### ISSUE THREAD

**Issue by nfts2me** [ApeironTsuka/node-webpmux#20]
I'm having an issue with the library:

With this code:

const WebP = require('node-webpmux');
let img = new WebP.Image();
await img.load(imgBuffer);
await img.initLib();
const frameData = await img.getFrameData(img.frames[0]);

![image](https://user-images.githubusercontent.com/109629895/220628322-0605e103-f208-46d7-bd70-c9ceb6c83ad6.png)

However, the frame has the VP8 property:
![image](https://user-images.githubusercontent.com/109629895/220628843-504ca816-22f2-45a7-8c35-00b853886a27.png)

**Comment by ApeironTsuka** [comment]
I should make types clearer in the readme, and probably do more checks for that. getFrameData() expects a frame index (in this case, 0) rather than the frame itself. Sorry about that. Going to fix that it doesn't throw an error.

**Comment by nfts2me** [comment]
Thank you.

I see now that it always tries to load "libwebp.wasm" from / , as least on React.
Is it possible to make it load "libwebp.wasm" from a different route or relative route?
If I don't put it on /libwebp.wasm, it crashes with a 404 error.

**Comment by ApeironTsuka** [comment]
That's odd. It should be trying to load it from a relative path already. It first loads libwebp.js, which in turn loads ./libwebp/libwebp.js (the bindings, in a subdirectory of the module), which itself should be loading libwebp.wasm from that same directory. I'm not sure why it would be trying to load it from the root directory unless React is mangling the paths somehow.
