### ISSUE TITLE
choosealicense

### ISSUE THREAD

**Issue by FredHappyface** [ApeironTsuka/node-webpmux#24]
Looks like your project doesnt have a license which makes using it a massive grey area 

Would you be able to add one please? :) 

https://choosealicense.com/licenses/

**Comment by ApeironTsuka** [comment]
Chose LGPL 3.0 to hopefully not conflict with anyone's current usage of this library. I had honestly never thought this project would hit the 90k-a-week downloads point, so I hadn't given much thought to a license until now.

**Comment by FredHappyface** [comment]
Awesome stuff! Thanks for that! 

And yeah it's really great, thank you for all of your time on this :)
