### ISSUE TITLE
Hey! Can you please turn this into a CommonJS module?

### ISSUE THREAD

**Issue by PurpShell** [ApeironTsuka/node-webpmux#3]
Hello! I am searching for a lightweight alternative to webpmux since it took **31 megabytes** on my system, just to parse two texts.. So I stumbled upon this, and i asked my friend to test it, but he had issues with updating to node 14.. 
Can you make it a commonjs module, or at least a branch for commonjs?

**Comment by PurpShell** [comment]
you can also make it node-webpmux-commonjs on npm for the commonjs module

**Comment by PurpShell** [comment]
I can help you if you want, and there will be a lot of people using this.

**Comment by PurpShell** [comment]
I already made a pr and made a package node-webpmux-commonjs

**Comment by ApeironTsuka** [comment]
You should be able to use ESM from as far back as Node v8.5.0, though I think it was locked behind the `--experimental-modules` flag until Node v14. If using this flag isn't an option, I'll swap over to CommonJS. Maybe with a .mjs wrapper.

The next major update (v2.0.0, finishing up on it) is going to have an optional WebAssembly module, which should be supported from Node v8 as well, if I recall correctly.

**Comment by PurpShell** [comment]
hey! i already made a pr, with nicer docs

**Comment by PurpShell** [comment]
using --experimental-modules is sadly not an option

**Comment by PurpShell** [comment]
because it will be referenced from another package

**Comment by ApeironTsuka** [comment]
XD Seems you had the same idea with the docs. Already have a Markdown version ready with the pending update, sorry about that. I'll push the whole thing in a bit after reading through the changes in the PR, as I _think_ I've tested everything. The formatting is going to be different (as I did this a few days ago) but I'll update some of the layout and wording from the PR in places.

**Comment by ApeironTsuka** [comment]
Pushed the big update. Everything I've tested has worked, but publishing to NPM can wait a day or two in case there's any issues.
